name: Build linux binaries
on:
  push:
    branches:
      - linux

jobs:
  build:
    name: Build executable
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install SDL2
        run: apt-get update && apt-get -y --no-install-recommends install g++ make libsdl2-dev
      - name: Make
        run: make
