name: Build linux binaries
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'tools/**'
jobs:
  build:
    name: Build executable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SDL2
        run: sudo apt-get update && sudo apt-get -y install libsdl2-dev
      - name: Build binaries
        run: make dist
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SIDFactoryII-linux
          path: ./artifacts/
