name: Build windows binaries
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'tools/**'
  workflow_dispatch:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'tools/**'
jobs:
  build:
    name: Build executable
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build binaries
        run: ./build_windows.bat
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SIDFactoryII-windows
          path: ./artifacts/
