name: Build linux binaries
on:
  push:
    branches:
      - linux

jobs:
  build:
    name: Build executable
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build binaries
        run: make ubuntu
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: SIDFactoryII-linux.zip
          path: ./artifacts/
